# Generated by Django 4.2.5 on 2023-09-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('patrimony', models.CharField(max_length=45)),
                ('allocable', models.BooleanField()),
                ('available', models.BooleanField(default=True)),
                ('warranty_expire', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
